# Site
repository: EgongD/EgongD.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이호세아
title: Backend Engineer
email: dlghtpdk@gmail.com
phone: 010-9356-7620

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  Egongd
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: 호-이-7b8779265
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 티스토리 기술 블로그
  icon: fas fa-globe
  url: https://coding-gongdae.tistory.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  .<br>
  <br>
  <br>
  <br>
  <strong>성실하고 꾸준하게 준비하고 나아가는 개발자</strong>가 되는 것이 저의 다짐이고,
  프로젝트를 통해 팀원들과 많은 소통으로 많은 문제를 해결했었기 때문에 <strong>팀원을 존중하고 소통하며 나아가는 개발 문화를 지향</strong>하겠습니다.
  

content:
  - title: Strength # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # title: 
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          늦었다고 생각했을 때 더 늦기 전에 해보고싶은걸 해보자!
        description: | # this will include new lines to allow paragraphs
          * <strong>분석업무를 하며 생긴 꼼꼼함</strong><br>
           : 환경부주관 정도관리(미지의 값이 주어졌을 때 실험을 통해 답을 도출해내는 시험) 수질, PCBs 분야 매년 통과.<br>
           : (통과하지 못하면 최대 면허정지 수준의 제제를 받을 수 있느 중요한 시험.)
           <br><br>
           
          * <strong>팀과의 협업 시 소통으로 문제를 빠르게 해결</strong><br>
           : 프리 프로젝트 시 소통의 부재로 개발하는 시간이 너무 오래 걸려 문제가 발생했던 경험이 있어서, 메인 프로젝트 때에는 프론트엔드, 백엔드 가리지 않고 상황을 공유하며 진행.<br>
           : 모르는 오류나 혼자 알아보고 공부하다 도저히 못풀겠는 오류나 문제들은 서로 공유해서 같이 알아보고 해결함.
           <br><br>
           
          * <strong>맡은 업무는 끝까지 수행함</strong><br>
           : 메인 프로젝트 시 처음 접하는 KakaoPay API를 이용해 카카오페이 테스트 결제 부분 구현.<br>
           : 구글링, 카카오디벨로터 질문 등 팀원들에게 양해를 구하고 약 10일 정도 시간을 소요함.<br>
           : 처음 해보는 기능이라 많이 어려웠지만 성공적으로 구현함.
           <br><br>
           
  - title: Skill
    layout: text
    content: | # this will include new lines to allow paragraphs
      * <strong>Java</strong>
      * <strong>Spring Boot</strong>, <strong>Spting MVC</strong>, <strong>Spring JPA</strong>, <strong>Spring JWT</strong>
      * <strong>IntelliJ</strong>
      * <strong>MySQL</strong>
      * <strong>AWS</strong>
      * <strong>Github</strong>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 왜 가?
        link: http://whystay.p-e.kr
        # link_text: boringcompany.com
        sub_title: 숙박목적에 따른 예약 플랫폼<br>
        sub_title: Frontend : 3명, Backend : 3명
        caption: 2023.01 - 2023.02
        quote: >
          프론트와의 소통으로 
        description: | # this will include new lines to allow paragraphs
          - <strong>Reservation 구현</strong><br>
            : Spring MVC를 이용한 CRUD 기능을 수행하는 부분 구현.
          <br><br>
          - <strong>Kakaopay API를 이용한 테스트 결제 구현</strong><br>
            : 대기업 API를 이용한 구현 방법 습득.
          <br><br>
          - <strong>AWS EC2를 이용한 배포</strong><br>
          <br><br>
          - <strong>DB 관리</strong><br>
            : Redis와 Doker를 이용한 DB 관리.<br>
          <br><br>
          - <strong>코드 분석</strong><br>
            : 팀원과의 회의 때 코드가 왜 이렇게 되었는지 뜯어보며 분석하고, 다른 팀원의 코드 스타일도 살펴 봄.
          <br><br>
          - <string>팀원들과의 호흡</strong><br>
            : 팀원들이 다 새벽 2시, 3시까지 남아서 프로젝트를 해서 정말 상시 소통이라고 말할 수 있을 정도로 많이 소통함.<br>
            : 매 주 3 ~ 4회 회의를 통한 진행상황 체크.<br>
            : 어려운 부분 또는 프론트와의 통신 문제로 인한 오류 발생 시 구글링, 회의를 통한 오류해결.<br>
            : 프로젝트 마무리 후 React로 작업한 프론트 코드를 보며 어떻게 했는지 코드를 뜯어봄.
            <br><br>
            
          KakaoPay관련 블로깅 내용 링크 : [https://coding-gongdae.tistory.com/42](https://coding-gongdae.tistory.com/42)
          <br><br>
            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠
        caption: 2022.08 - 2023.02
        sub_title: Backend Engnieering 41기
        description: | # this will include new lines to allow paragraphs
          코딩 기초, Spring JDBC, Spring JPA, Spring JWT, 알고리즘, 배포환경 등
          
      - layout: left
        title: 국립한국교통대학교
        caption: 2011.03 - 2017.02
        sub_title: 환경공학과, 친환경에너지(부전공)
        description: | # this will include new lines to allow paragraphs
          3학년부터 성적우수 장학금 수령.
          


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
