# Site
repository: EgongD/EgongD.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이호세아
title: Backend Engineer
email: dlghtpdk@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  Egongd
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: https://www.linkedin.com/in/호-이-7b8779265/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 티스토리 기술 블로그
  icon: fas fa-globe
  url: https://coding-gongdae.tistory.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  비전공자에서 개발의 세계로 넘어온 이호세아 입니다. <br>
  이런저런 자기 개발을하며 회사생활을 하고 있었는데 Java 입문 수업을 듣고 '앗! 너무 재미있다! 더 배우고 싶다!'라는 생각에 코드스테이츠로 코딩을 본격적으로 배우기 시작했습니다.<br><br>
  처음 코딩을 접했을 때 사람들을 편리하게 생활할 수 있게 해주는 기술에 매력을 느꼈습니다. 늦게(?) 입문한 만큼 더 <strong>성실하고 꾸준하게 준비하고 나아가는 개발자</strong>가 되는 것이
  저희 다짐이고, 항상 <strong>팀원을 존중하고 소통하며 나아가는 개발 문화를 지향</strong>하겠습니다.
  

content:
  - title: Strength # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # title: 
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          늦었다고 생각했을 때 더 늦기 전에 해보고싶은걸 해보자!
        description: | # this will include new lines to allow paragraphs
          * <strong>분석업무를 약 4년정도 할 정도로 꼼꼼함</strong><br>
           : 정밀하게 집중해서 업무에 임해야 되는 분석업무를 꼼꼼하게 수행함.
           <br><br>
           
          * <strong>팀과의 협업시 소통으로 문제를 빠르게 해결</strong><br>
           : 프리 프로젝트 시 소통의 부재로 개발하는 시간이 너무 오래 걸려 문제가 발생했던 경험이 있어서, 메인 프로젝트 때에는 프론트엔드, 백엔드 가리지 않고 상황을 공유하며 진행했습니다.
           이에 별 탈 없이 프로젝트를 마무리함.
           <br><br>
           
          * <strong>맡은 업무는 끝까지 수행함</strong><br>
           : 메인 프로젝트 시 처음 접하는 KakaoPay API를 이용해 카카오페이 테스트 결제 부분 구현.
           <br><br>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 왜 가?
        link: http://whystay.p-e.kr
        # link_text: boringcompany.com
        sub_title: 숙박목적에 따른 예약 플랫폼
        caption: 2023.01 - 2023.02
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - <strong>Reservation 구현</strong><br>
            : Spring MVC를 이용한 CRUD 기능을 수행하는 부분 구현.
          <br><br>
          - <strong>Kakaopay API를 이용한 테스트 결제 구현</strong><br>
            : 대기업 API를 이용한 구현 방법 습득.
          <br><br>
          - <strong>AWS EC2를 이용한 배포</strong><br>
          <br><br>
          - <strong>DB 관리</strong><br>
            : Redis와 Doker를 이용한 DB 관리.<br>
          <br><br>
          - <strong>코드 분석</strong><br>
            : 팀원과의 회의 때 코드가 왜 이렇게 되었는지 뜯어보며 분석하고, 다른 팀원의 코드 스타일도 살펴 봄.
          <br><br>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠
        caption: 2022.08 - 2023.02
        sub_title: Backend Engnieering 41기
        description: | # this will include new lines to allow paragraphs
          학점 : 코딩기초, Java Spring을 기반으로 한 내용, 알고리즘, 배포환경 등
          
      - layout: left
        title: 국립한국교통대학교
        caption: 2011.03 - 2017.02
        sub_title: 환경공학과, 친환경에너지(부전공)
        description: | # this will include new lines to allow paragraphs
          3.82/4.5 학점, 부전공으로 친환경에너지를 전공하였습니다. <br>
          3학년부터 성적우수 장학금 수령.
          

  - title: Skill
    layout: text
    content: | # this will include new lines to allow paragraphs
      * <strong>Java</strong>
      * <strong>Spring Boot</strong>, <strong>Spting MVC</strong>, <strong>Spring JPA</strong>, <strong>Spring JWT</strong>
      * <strong>IntelliJ</strong>
      * <strong>MySQL</strong>
      * <strong>AWS</strong>
      * <strong>Github</strong>


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
